services:
  backend:
    image: nobugsme/nbank:preprod_version
    container_name: backend
    ports:
      - "4111:4111"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nbank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - FRAUD_DETECTION_SERVICE_URL=http://wiremock:8080
    depends_on:
      - postgres
    networks:
      - nbank-network

  frontend:
   image: nobugsme/nbank-ui:preprod_version
   container_name: frontend
   ports:
     - "3000:80"
   networks:
    - nbank-network
   depends_on:
    - backend
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nbank"]
      interval: 10s
      timeout: 5s
      retries: 5

  wiremock:
    image: wiremock/wiremock:3.13.1
    container_name: wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    networks:
      - nbank-network
  selenoid:
    image: adtechqatools/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/selenoid:ro
      - ./video:/opt/selenoid/video
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/alekseikokarev/Projects/video
    command:
      - "-container-network"
      - "nbank-network"
      - "-video-output-dir"
      - "/opt/selenoid/video"
    networks:
      - nbank-network
    depends_on:
      - frontend

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    depends_on:
      - selenoid
    command:
      - "--selenoid-uri=http://selenoid:4444"
    ports:
      - "8080:8080"
    networks:
      - nbank-network
      
networks:
  nbank-network:
    name: nbank-network

volumes:
  postgres_data:
    driver: local
