#Application
host=http://localhost:4111
api_version=/api/v1/
#Users
admin_username=admin
admin_password=admin
#SelenideSetup
remote_host=http://localhost:4444/wd/hub
ui_baseurl=http://192.168.0.127:3000
browser=chrome
resolution=1920x1080