# Format: RequestClass=ResponseClass:fieldRequest=STANDARD_EQUALS, fieldResponse:REQUIRED
# See more details in models.comparison.FieldRule

CreateUserRequest=UsersResponse:\
  id=REQUIRED,\
  username=STANDARD_EQUALS,\
  password=REQUIRED,\
  name=CHECK_NULL,\
  role=REQUIRED,\
  accounts=ARRAY_EMPTY

UserAccountCreate=UserAccountResponse:\
id=dREQUIRED,\
accountNumber=REQUIRED,\
balance=REQUIRED,\
transactions=ARRAY_EMPTY

DepositRequest=UserAccountResponse:\
  id=STANDARD_EQUALS,\
  accountNumber=REQUIRED,\
  balance=REQUIRED,\
  transactions=ARRAY_NOT_EMPTY

TransferRequest=TransferResponse:\
amount=STANDARD_EQUALS,\
senderAccountId=STANDARD_EQUALS,\
receiverAccountId=STANDARD_EQUALS


#CreateUserRequest=UsersResponse:\
#  id=REQUIRED\
#  username=STANDARD_EQUALS\
#  role=REQUIRED\
#  password=REQUIRED\
#  name=CHECK_NULL\
#  accounts=ARRAY_EMPTY

#TransferRequest=TransferResponse:amount=GREATER_THAN:0,senderAccount.id=STANDARD_EQUALS,receiverAccount.id=STANDARD_EQUALS

UserCheck=UserResponse:user.address.city=STANDARD_EQUALS,isActive=CHECK_TRUE