# Format: RequestClassDTO=ResponseClassDAO:fieldRequest=STANDARD_EQUALS, fieldResponse:REQUIRED
# See more details in models.comparison.FieldRule

UsersResponse=CustomersDao:\
  id=REQUIRED,\
  username=STANDARD_EQUALS,\
  password=REQUIRED,\
  name=STANDARD_EQUALS,\
  role=STANDARD_EQUALS,\
  createdAt=REQUIRED

UserAccountResponse=AccountsDao:\
  id=STANDARD_EQUALS,\
  accountNumber=STANDARD_EQUALS,\
  balance=STANDARD_EQUALS,\
  createdAt=REQUIRED,\
  updatedAt=REQUIRED