# Positive test: user can transfer all money to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
"id": 2,
"balance": 5000
}

### Main step 3: second user transfer 10000 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 10000
}

### Main step 3: check updated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check updated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Positive test: user can transfer money between his accounts
### Precondition step: Authorized user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: Authorized user creates one more account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: deposit 0.01 money into first user account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
{
  "id": 1,
  "balance": 0.01
}

### Main step 2: transfer 0.01 money from first account to second account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0.01
}

### Main step 3: check updated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: check updated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Positive test: user can transfer money to some else's user with two existed accounts
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 3,
  "balance": 5000
}

### Main step 2: second user transfer 2500 money to second account first user
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 2500
}

### Main step 3: check updated balance (amount) on second user account
GET /api/v1/accounts/3/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check updated balance (amount) on second account first user
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 6: check unupdated balance (amount) on first account first user
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer money from account with zero balance
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user transfer 1 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 1
}

### Main step 2: check unupdated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 3: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 4: check unupdated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer negative value to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user transfer -1000 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": -1000
}

### Main step 3: check unupdated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check unupdated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer zero money to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user transfer zero money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 0
}

### Main step 3: check unupdated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check unupdated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer money more than maximum limit to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 3: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 4: second user transfer 10000.01 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 10000.01
}

### Main step 5: check unupdated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 6: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 7: check unupdated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

# Negative test: user cannot transfer money from some else's existed account to his own
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: first user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 5000
}

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user transfer 4999 money from first user account to himself
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 4999
}

### Main step 3: check unupdated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check unupdated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer money from/to same his account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: first user deposit 1000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 1000
}

### Main step 1: user transfer 100 money from/to same account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 1,
  "receiverAccountId": 1,
  "amount": 100
}

### Main step 2: check unupdated balance (amount) on user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer money to non existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: first user deposit 1000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 1000
}

### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: find maximum existed account id
GET /api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 1: user transfer 100 money to non existed account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
{
  "senderAccountId": 1,
  "receiverAccountId": 10000, //maximum_id_account + 1
  "amount": 100
}

### Main step 2: check unupdated balance (amount) on user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer money from non existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: first user deposit 1000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 1,
  "balance": 1000
}

### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: find maximum existed account id
GET /api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 1: user transfer 100 money to non existed account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
{
  "senderAccountId": 10000, //maximum_id_account + 1
  "receiverAccountId": 1,
  "amount": 100
}

### Main step 2: check unupdated balance (amount) on user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Positive test: user can transfer 0.01 to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 0.01 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 0.01
}

### Main step 2: second user transfer 0.01 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 0.01
}

### Main step 3: check updated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check updated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

# Positive test: user can transfer 9999.99 to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 3: second user transfer 9999.99 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 9999.99
}

### Main step 3: check updated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 4: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 5: check updated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=


# Negative test: user cannot transfer 10000.01 to some else's existed account
### Precondition step: get auth token by admin
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
### Precondition step: admin creates a new first user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user1",
  "password": "Password1!",
  "role": "USER"
}
### Precondition step: admin creates a new second user
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "user2",
  "password": "Password1!",
  "role": "USER"
}

### Precondition step: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Precondition step: Authorized first user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Precondition step: get auth token by second user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Password1!"
}

### Precondition step: Authorized second user creates an account
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic a2F0ZTE5OTgxOmthdGUxOTk4MQ==

### Main step 1: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 2: second user deposit 5000 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 5000
}

### Main step 3: second user deposit 100 money into his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 2,
  "balance": 100
}

### Main step 3: second user transfer 10000.01 money to first user account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 10000.01
}

### Main step 4: check unupdated balance (amount) on second user account
GET /api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Main step 5: get auth token by first user
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "Password1!"
}

### Main step 6: check unupdated balance (amount) on first user account
GET /api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

